apiVersion: template.openshift.io/v1
kind: Template
labels:
  createdBy: gitlab-runner-template
metadata:
  name: gitlab-runner
  annotations:
    description: |
      GitLab Runner Service.
      It uses GitLab Runner image from official repository at docker hub.
      https://hub.docker.com/r/gitlab/gitlab-runner/
      Before you start, please setup Security Context Constraints (SCC) for service accounts used for running
      containers
        oc login -u system:admin
        oc adm policy add-scc-to-user privileged -z gitlab-runner-user -n CURRENT_PROJECT_NAME
    iconClass: "fa fa-git"
    tags: "gitlab,CI"
parameters:
  - description: "The name for the application. The service will be named like the application."
    displayName: "Application name."
    name: APPLICATION_NAME
    value: "gitlab-runner"
    required: true
  - description: "URL that GitLab can be reached at"
    displayName: "GitLab URL"
    name: GITLAB_URL
    required: true
  - description: "Runner Registration Token from the GitLab app"
    displayName: "Registration Token."
    name: REGISTRATION_TOKEN
    required: true
  - description: "URL that GitLab registry can be reached at"
    displayName: "GitLab Registry URL"
    name: GITLAB_REGISTRY_URL
    required: true
  - description: Custom username or access key of 5 to 20 characters in length.
    displayName: Minio Cloud Storage Access Key
    name: MINIO_ACCESS_KEY
    from: "[a-zA-Z0-9]{20}"
    generate: expression
  - description: Custom password or secret key of 8 to 40 characters in length.
    displayName: Minio Cloud Storage Secret Key
    name: MINIO_SECRET_KEY
    from: "[a-zA-Z0-9]{40}"
    generate: expression
  - description: "Http Proxy"
    displayName: "Http Proxy"
    name: HTTP_PROXY
    required: false
  - description: "Https Proxy"
    displayName: "Https Proxy"
    name: HTTPS_PROXY
    required: false
  - description: "Ftp Proxy"
    displayName: "Ftp Proxy"
    name: FTP_PROXY
    required: false
  - description: "No Proxy"
    displayName: "No Proxy"
    name: NO_PROXY
    required: false

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: gitlab-runner
      labels:
        app: ${APPLICATION_NAME}
    spec:
      tags:
        - name: v11.11.1
          from:
            kind: DockerImage
            name: gitlab/gitlab-runner:v11.11.1

  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}-scripts
      labels:
        app: ${APPLICATION_NAME}
    data:
      entrypoint: |
        #!/bin/bash
        set -xe
        cp /scripts/config.toml /etc/gitlab-runner/
        # import root ca cert
        cp /scripts/ca.crt /usr/local/share/ca-certificates/
        update-ca-certificates
        # Register the runner
        /entrypoint register --non-interactive \
          --url $GITLAB_URL \
          --run-untagged \
          --kubernetes-privileged \
          --registration-token $REGISTRATION_TOKEN \
          --name "k8s_runner" \
          --executor kubernetes \
          --env HTTP_PROXY="$HTTP_PROXY" \
          --env http_proxy="$HTTP_PROXY" \
          --env HTTPS_PROXY="$HTTPS_PROXY" \
          --env https_proxy="$HTTPS_PROXY" \
          --env FTP_PROXY="$FTP_PROXY" \
          --env ftp_proxy="$FTP_PROXY" \
          --env NO_PROXY="$NO_PROXY" \
          --env no_proxy="$NO_PROXY"
        # Add minio config
        sed -i '/\[runners.cache\]/a\
            Type = "s3"\
            Shared = true' /etc/gitlab-runner/config.toml
        sed -i '/\[runners.cache.s3\]/a\
              ServerAddress = "'$MINIO_URL'"\
              AccessKey = "'$MINIO_ACCESS_KEY'"\
              SecretKey = "'$MINIO_SECRET_KEY'"\
              BucketName = "gitlab-runner-cache"\
              Insecure = true' /etc/gitlab-runner/config.toml
        # Start the runner
        /entrypoint run --user=gitlab-runner \
          --working-directory=/home/gitlab-runner

      config.toml: |
        concurrent = 10
        check_interval = 10

      ca.crt: |
        -----BEGIN CERTIFICATE-----
        MIIF2DCCA8CgAwIBAgIQdpa0Bmhnp41D2A88iZzyujANBgkqhkiG9w0BAQsFADBs
        MRIwEAYKCZImiZPyLGQBGRYCaGsxEzARBgoJkiaJk/IsZAEZFgNvcmcxFTATBgoJ
        kiaJk/IsZAEZFgVoYWRldjEqMCgGA1UEAxMhSG9zcGl0YWwgQXV0aG9yaXR5IFRy
        aWFsIFJvb3QgQ0ExMB4XDTE2MDIxMjA0MTUzOVoXDTM2MDIyNDAzMzczMlowbDES
        MBAGCgmSJomT8ixkARkWAmhrMRMwEQYKCZImiZPyLGQBGRYDb3JnMRUwEwYKCZIm
        iZPyLGQBGRYFaGFkZXYxKjAoBgNVBAMTIUhvc3BpdGFsIEF1dGhvcml0eSBUcmlh
        bCBSb290IENBMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAORVsk2X
        nmX4m5fBkHmVFwJkMMTP0iNj20BhRECLyOt3tv7EOVaSOSQkOBJ0QaZ62hyiv/rp
        NL9S2Fym6TmiZyoLoSufP/NgdyQKyAmMUb+cxbf/AIjfiQ05eb3J6S1Z9GC2lF4C
        Fb8wCx1Ui13HG0seX1OlLZLm0eSM2J0BUf4TEZtLM231a90I6J08K+BvmD5qvzXg
        w8c9D758WUz1bSV6Zws7ep4q8PEWM49siQpbwhyuR4akr46DBn9vxAhecux3v5kI
        KKt1+6twywsRNq40DtuYBK5uFDbzqqbLsxpk0jCG2iFygEl3cJBEQ2RVnqkXrIhr
        foLAIwFG63Gbe9i+SP2UNbDG5k0X8jilX9AJojnsSjo12APon+Ow+VjtncrG7Lxu
        qnj+Mt3jHAsw26ElblEpUcJj4UhcIPVxsTLF+BgCD2QbSDf3ogNCXI71aPtt2KyJ
        GsmSBunxYaeercSoMPDSgNF1GUZpFeqJhLZ062T810TuSBW5eb7Ug0ND+KOcw8Dd
        apNbCRv7qbhu1N0iP2tAkviSXa8006uFOBwJl+v6g80Y4GGDaN5rJLHki87QXtd3
        BRPpgddJx4VNtRL0KYhX6r5TKf8QZ3YzGrl5C6IcStSU88XRGh5fJ8RK5pUPND6H
        uiLqEJVnA9TR9UjXRGtRZIbGUborm3/dT4EDAgMBAAGjdjB0MAsGA1UdDwQEAwIB
        hjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRtL53Gl4idW1TYzrifDlHMfgXz
        DTAQBgkrBgEEAYI3FQEEAwIBATAjBgkrBgEEAYI3FQIEFgQU+oUEttkcmmR+LFqA
        IWi/nB67ankwDQYJKoZIhvcNAQELBQADggIBAH3KMddeRoLf+f7UlcGoaFGNRbb+
        cBxaLEAQkN8yBMg++3bgEcbFhkjjrnbJkOd29NYGQCTca1Rsi3GzrUovaUSefdlP
        d0qU1GpYelcCp9dW1OvbPnkoGZ19uKiW0ZgX5C3zxRirQpreHoGa6Qd2Sq2038jB
        MaTODvAgZngbFBLuLUQic47NEWhbhr6wcf38jc0gDAITxzEbWjZfHOm34h+n39Rw
        dquYX6YqfZCqP2IDBzx5RHdlNJ08posPPHScQ9yGQrikSDG/ELLQNDacV0EqugIB
        eO12maqlhRytStxFLP83VLlWqhjsxckJi2zDiwkEtqzMZdTlUCH/oJsdN41ew1ta
        Pq9Zdfxs0ggDA6YzEpvlps8xM0joS+6Wit6al00xVI8UN/dEjaEBtEzIwVOHu7D1
        ExNgJBQfe3QUtgD/hofVD8JIob7ty7TXw6qngtsMLH+zdvexPkdtYrClG8ueghp+
        +AA+TjG68BO9k8Q48ZCjntbkCJT2CmqcTy+2sBTrR0VEKftCwaDYdp6ma0m2IIK0
        aoU2vgbT7k9IZNS/CpTSOl8K2U/R9LY2OHIfvro8Xx1zrkwu8JM/O88NQ2E8Jhz/
        ngX+fm3bQgU59aNE8ojLJnwsSKP608nM1Gk2S21Cv/fYgDzTzF6m6KBFn77Cspez
        ppo9JiL12R+xlm48
        -----END CERTIFICATE-----

  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}-user
      labels:
        app: ${APPLICATION_NAME}

  - kind: RoleBinding
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}-edit
      labels:
        app: ${APPLICATION_NAME}
    subjects:
      - kind: ServiceAccount
        name: ${APPLICATION_NAME}-user
    roleRef:
      name: edit

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      strategy:
        type: Recreate
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - gitlab-runner
            from:
              kind: ImageStreamTag
              name: gitlab-runner:v11.11.1
      replicas: 1
      test: false
      selector:
        app: ${APPLICATION_NAME}
        deploymentconfig: ${APPLICATION_NAME}
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            deploymentconfig: ${APPLICATION_NAME}
        spec:
          volumes:
            - name: scripts
              configMap:
                name: ${APPLICATION_NAME}-scripts
          containers:
            - name: gitlab-runner
              image: gitlab-runner
              command: ["/bin/bash", "/scripts/entrypoint"]
              ports:
                - containerPort: 22
                  protocol: TCP
                - containerPort: 80
                  protocol: TCP
              env:
                - name: GITLAB_URL
                  value: ${GITLAB_URL}
                - name: REGISTRATION_TOKEN
                  value: ${REGISTRATION_TOKEN}
                - name: GITLAB_REGISTRY_URL
                  value: ${GITLAB_REGISTRY_URL}
                - name: MINIO_ACCESS_KEY
                  value: ${MINIO_ACCESS_KEY}
                - name: MINIO_SECRET_KEY
                  value: ${MINIO_SECRET_KEY}
                - name: MINIO_URL
                  value: ${APPLICATION_NAME}-cache
                - name: KUBERNETES_PRIVILEGED
                  value: "true"
                - name: KUBERNETES_IMAGE
                  value: "ubuntu:16.04"
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: "metadata.namespace"
                - name: HTTP_PROXY
                  value: ${HTTP_PROXY}
                - name: HTTPS_PROXY
                  value: ${HTTPS_PROXY}
                - name: FTP_PROXY
                  value: ${FTP_PROXY}
                - name: NO_PROXY
                  value: ${NO_PROXY}
              resources:
                limits:
                  cpu: "600m"
                  memory: "600Mi"
                requests:
                  cpu: "100m"
                  memory: "300Mi"
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
              readinessProbe:
                exec:
                  command: ["/usr/bin/pgrep", "gitlab-runner"]
                initialDelaySeconds: 10
              livenessProbe:
                exec:
                  command: ["/usr/bin/pgrep", "gitlab-runner"]
                initialDelaySeconds: 60
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: IfNotPresent
              securityContext:
                privileged: true
                runAsUser: 0
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccount: ${APPLICATION_NAME}-user

  ### minio integration for cache
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: minio
      labels:
        app: ${APPLICATION_NAME}
    spec:
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: minio/minio:latest

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}-cache
      labels:
        app: ${APPLICATION_NAME}
    spec:
      type: ClusterIP
      ports:
        - name: http
          nodePort: 0
          port: 80
          protocol: TCP
          targetPort: 9000
      selector:
        app: ${APPLICATION_NAME}
        deploymentconfig: ${APPLICATION_NAME}-cache

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${APPLICATION_NAME}-cache
      labels:
        app: ${APPLICATION_NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}-cache
      labels:
        app: ${APPLICATION_NAME}
    spec:
      replicas: 1
      selector:
        app: ${APPLICATION_NAME}
        deploymentconfig: ${APPLICATION_NAME}-cache
      strategy:
        type: Recreate
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - minio
            from:
              kind: ImageStreamTag
              name: minio:latest
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            deploymentconfig: ${APPLICATION_NAME}-cache
        spec:
          containers:
            - name: minio
              ports:
                - containerPort: 9000
                  name: http
                  protocol: TCP
              env:
                - name: MINIO_ACCESS_KEY
                  value: ${MINIO_ACCESS_KEY}
                - name: MINIO_SECRET_KEY
                  value: ${MINIO_SECRET_KEY}
              command:
                - /bin/sh
                - "-c"
                - >-
                  /bin/mkdir -p /storage/gitlab-runner-cache; 
                  /usr/bin/minio server /storage
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
              volumeMounts:
                - name: storage
                  mountPath: /storage
              readinessProbe:
                exec:
                  command: ["/usr/bin/pgrep", "minio"]
                initialDelaySeconds: 5
                timeoutSeconds: 1
              livenessProbe:
                tcpSocket:
                  port: 9000
                initialDelaySeconds: 15
                timeoutSeconds: 10
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccount: ${APPLICATION_NAME}-user
          volumes:
            - name: storage
              persistentVolumeClaim:
                claimName: ${APPLICATION_NAME}-cache
